### ISSUE TITLE
Unable to update from 7.0.1 to 7.3.0 using MSI installer

### ISSUE THREAD

**Issue by divyakrishna1** [elastic/windows-installers#328]
![image](https://user-images.githubusercontent.com/19267121/62749769-a7051900-ba2b-11e9-9cbc-302d7c87effe.png)

Unable to upgrade from 7.0.1 to 7.3.0.  Can you all please take a look at it and let me if im missing anything ?
Attached is the MSI.Log
[elasticsearch-7.3.0.install_new.log](https://github.com/elastic/windows-installers/files/3484475/elasticsearch-7.3.0.install_new.log)

**Comment by russcam** [comment]
@divyakrishna1 The error message indicates that the elasticsearch.yml found in the `%ES_PATH_CONF%` directory was detected as invalid. Can you post the contents of that file?

**Comment by divyakrishna1** [comment]
@russcam 
Thanks for responding.  Below is the content.
### 
**bootstrap.memory_lock: false
cluster.name: dev-elk
http.port: 9200
network.host: X.X.X.X
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: elk-dev1
path.data: D:\Elastic\Elasticsearch\Data
path.logs: D:\Elastic\Elasticsearch\logs
path.repo: ["\\\\X.X.X.X\\ELK_Repo_Backup"]
transport.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: true
cluster.initial_master_nodes: X.X.X.X
thread_pool.search.queue_size: 10000
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: certs/elastic-stack-ca.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-stack-ca.p12
xpack.security.transport.ssl.verification_mode: certificate
xpack.watcher.enabled: true
xpack.watcher.index.rest.direct_access: true**

**Comment by russcam** [comment]
The yml provided isn't valid YAML. If you paste it into [YAML Lint](http://www.yamllint.com/) for example, there's a problem on line 12:

```
(<unknown>): found unknown escape character while parsing a quoted scalar at line 12 column 13
```

There are few errors in the YAML:

1. If using double quotes, you need to escape `\` characters inside quotes with `\`. It would be better in the case of `path.repo` to not quote or use single quotes.
2. cluster.initial_master_nodes is a sequence rather than a scalar value, so needs to be either a flow or block sequence.

If the YAML is fixed to be valid, you'll be able to upgrade:

```yaml
bootstrap.memory_lock: false
cluster.name: dev-elk
http.port: 9200
network.host: X.X.X.X
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: elk-dev1
path.data: D:\Elastic\Elasticsearch\Data
path.logs: D:\Elastic\Elasticsearch\logs
path.repo: [\\X.X.X.X\ELK_Repo_Backup]
transport.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: true
cluster.initial_master_nodes: [X.X.X.X]
thread_pool.search.queue_size: 10000
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: certs/elastic-stack-ca.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-stack-ca.p12
xpack.security.transport.ssl.verification_mode: certificate
xpack.watcher.enabled: true
xpack.watcher.index.rest.direct_access: true
```
